module.exports = {
  eslintVueDev: [
    "eslint",
    "eslint-config-prettier",
    "eslint-config-standard",
    "eslint-friendly-formatter",
    "eslint-loader",
    "eslint-plugin-import",
    "eslint-plugin-node",
    "eslint-plugin-prettier",
    "eslint-plugin-promise",
    "eslint-plugin-standard",
    "eslint-plugin-vue",
  ],
  eslintReactDev: [
    "eslint",
    "eslint-config-airbnb",
    "eslint-config-prettier",
    "eslint-plugin-babel",
    "eslint-plugin-compat",
    "eslint-plugin-import",
    "eslint-plugin-jsx-a11y",
    "eslint-plugin-markdown",
    "eslint-plugin-react",
    "eslint-plugin-react-hooks",
  ],
  validateCommitMsg: {
    types: [
      "feat",
      "fix",
      "docs",
      "style",
      "refactor",
      "perf",
      "test",
      "build",
      "ci",
      "chore",
      "revert",
    ],
    scope: {
      required: false,
      allowed: ["*"],
      validate: false,
      multiple: false,
    },
    warnOnFail: false,
    maxSubjectLength: 100,
    subjectPattern: ".+",
    subjectPatternErrorMsg: "subject does not match subject pattern!",
    helpMessage: "",
    autoFix: false,
  },
};
